version: '3.1'
services:

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_DATABASE: task-manager-api
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

  web:
    build: .
    ports:
      - 3000:3000
    networks:
      - app-network
    volumes:
      - appdata:/avatars

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  appdata: